import { CopilotClient, defineTool } from "@github/copilot-sdk";
import * as readline from "readline";

/**
 * Security Analysis Agent
 *
 * Automated security vulnerability scanning using GitHub Copilot SDK.
 * Checks for OWASP Top 10, dependency vulnerabilities, secrets exposure.
 */

const scanForVulnerabilities = defineTool("scan_vulnerabilities", {
    description: "Scan code for security vulnerabilities based on OWASP Top 10",
    parameters: {
        type: "object",
        properties: {
            code: { type: "string", description: "Code to scan" },
            language: { type: "string", description: "Programming language" },
            scanType: {
                type: "string",
                description: "Scan type: injection, auth, xss, secrets, dependencies, all",
            },
        },
        required: ["code", "language"],
    },
    handler: async ({ code, language, scanType }) => {
        const vulnerabilities = [];

        // Simulated security scanning
        const patterns = {
            injection: /(\bexec\b|\beval\b|\bsystem\b|\$\{.*\})/gi,
            secrets: /(api[_-]?key|password|secret|token)\s*[=:]\s*['"]/gi,
            xss: /(innerHTML|document\.write|\.html\()/gi,
        };

        for (const [type, pattern] of Object.entries(patterns)) {
            if (scanType && scanType !== "all" && scanType !== type) continue;
            const matches = code.match(pattern);
            if (matches) {
                vulnerabilities.push({
                    type,
                    severity: type === "secrets" ? "critical" : "high",
                    findings: matches.length,
                    message: `Found ${matches.length} potential ${type} vulnerability pattern(s)`,
                });
            }
        }

        return {
            language,
            scanType: scanType || "all",
            vulnerabilities,
            summary: `Scanned ${code.length} characters. Found ${vulnerabilities.length} vulnerability category(s).`,
        };
    },
});

const prepareSecurityReport = defineTool("prepare_security_report", {
    description: "Prepare a security report from scan findings",
    parameters: {
        type: "object",
        properties: {
            title: { type: "string", description: "Report title" },
            findings: { type: "string", description: "JSON string of findings" },
            recommendation: { type: "string", description: "Remediation recommendation" },
        },
        required: ["title", "findings", "recommendation"],
    },
    handler: async ({ title, findings, recommendation }) => {
        const report = `## Security Report: ${title}

**Generated:** ${new Date().toISOString()}

### Findings
${findings}

### Recommendations
${recommendation}

---
*Generated by Security Analysis Agent*`;

        return { status: "report_prepared", report };
    },
});

async function startSecurityAnalysisAgent() {
    console.log("🛡️ Security Analysis Agent starting...\n");

    const client = new CopilotClient();

    const session = await client.createSession({
        model: "gpt-4o",
        streaming: true,
        tools: [scanForVulnerabilities, prepareSecurityReport],
        mcpServers: {
            github: {
                type: "http",
                url: "https://api.githubcopilot.com/mcp/",
            },
        },
        systemPrompt: `You are a security analysis expert. Your role is to:
1. Scan code for security vulnerabilities (OWASP Top 10)
2. Check for hardcoded secrets and credentials
3. Identify injection vulnerabilities (SQL, XSS, command injection)
4. Assess authentication and authorization flaws
5. Prepare security reports with remediation guidance

Use scan_vulnerabilities to analyze code and prepare_security_report to format findings.
Be thorough and prioritize critical/high severity issues.`,
    });

    session.on("assistant.message_delta", (event) => {
        process.stdout.write(event.data.deltaContent);
    });

    session.on("tool.call", (event) => {
        console.log(`\n🔧 [Tool Call: ${event.data.toolName}]`);
    });

    session.on("tool.result", (event) => {
        console.log(`✅ [Tool Result: ${event.data.toolName}]`);
    });

    const rl = readline.createInterface({
        input: process.stdin,
        output: process.stdout,
    });

    console.log("🚀 Security Analysis Agent Ready!");
    console.log("=".repeat(60));
    console.log("\nPaste code or describe what you want analyzed for security issues.");
    console.log("Type 'exit' to quit\n");
    console.log("=".repeat(60) + "\n");

    const prompt = () => {
        rl.question("You: ", async (input) => {
            if (input.toLowerCase() === "exit") {
                console.log("\n👋 Shutting down Security Analysis Agent...");
                await client.stop();
                rl.close();
                return;
            }
            if (!input.trim()) { prompt(); return; }
            process.stdout.write("\nAssistant: ");
            await session.sendAndWait({ prompt: input });
            console.log("\n");
            prompt();
        });
    };

    process.stdout.write("Assistant: ");
    await session.sendAndWait({
        prompt: "Hello! Introduce yourself and explain how you can help with security analysis.",
    });
    console.log("\n");
    prompt();
}

startSecurityAnalysisAgent().catch((error) => {
    console.error("❌ Error starting Security Analysis Agent:", error);
    process.exit(1);
});
